const cations = [
    "H⁺", "NH₄⁺", "Li⁺", "Na⁺", "K⁺",
    "Ag⁺", "Hg⁺", "Hg²⁺", "Ba²⁺", "Ca²⁺",
    "Mg²⁺", "Zn²⁺", "Mn²⁺", "Sn²⁺", "Pb²⁺",
    "Cu²⁺", "Ni²⁺", "Co²⁺", "Cd²⁺", "Fe²⁺",
    "Fe³⁺", "Al³⁺", "Cr³⁺", "Bi³⁺", "Sr²⁺"
];

const solubilityData = {
    "O²⁻": [
        { value: 18, color: "blue" },
        { value: "-", color: "white" },
        { value: 30, color: "gray" },
        { value: 62, color: "gray" },
        { value: 94, color: "gray" },
        { value: 232, color: "pink" },
        { value: 418, color: "pink" },
        { value: 217, color: "pink" },
        { value: 153, color: "gray" },
        { value: 56, color: "gray" },
        { value: 40, color: "gray" },
        { value: 81, color: "pink" },
        { value: 71, color: "pink" },
        { value: 135, color: "pink" },
        { value: 223, color: "pink" },
        { value: 80, color: "pink" },
        { value: 75, color: "pink" },
        { value: 75, color: "pink" },
        { value: 128, color: "pink" },
        { value: 72, color: "pink" },
        { value: 160, color: "pink" },
        { value: 102, color: "pink" },
        { value: 152, color: "pink" },
        { value: 466, color: "pink" },
        { value: 104, color: "gray" }
    ],
    "OH⁻": [
        { value: 18, color: "blue" },
        { value: 35, color: "blue" },
        { value: 24, color: "blue" },
        { value: 40, color: "blue" },
        { value: 56, color: "blue" },
        { value: 125, color: "orange" },
        { value: 218, color: "orange" },
        { value: 235, color: "orange" },
        { value: 171, color: "blue" },
        { value: 74, color: "green" },
        { value: 58, color: "pink" },
        { value: 99, color: "pink" },
        { value: 89, color: "pink" },
        { value: 158, color: "pink" },
        { value: 241, color: "pink" },
        { value: 98, color: "pink" },
        { value: 93, color: "pink" },
        { value: 93, color: "pink" },
        { value: 146, color: "pink" },
        { value: 90, color: "pink" },
        { value: 107, color: "pink" },
        { value: 78, color: "pink" },
        { value: 103, color: "pink" },
        { value: 260, color: "pink" },
        { value: 122, color: "blue" }
    ],
    "F⁻": [
        { value: 20, color: "blue" },
        { value: 37, color: "blue" },
        { value: 26, color: "green" },
        { value: 42, color: "blue" },
        { value: 58, color: "blue" },
        { value: 127, color: "blue" },
        { value: 220, color: "green" },
        { value: 239, color: "gray" },
        { value: 175, color: "green" },
        { value: 78, color: "pink" },
        { value: 62, color: "yellow" },
        { value: 103, color: "blue" },
        { value: 93, color: "blue" },
        { value: 157, color: "blue" },
        { value: 245, color: "pink" },
        { value: 102, color: "blue" },
        { value: 97, color: "blue" },
        { value: 97, color: "blue" },
        { value: 150, color: "yellow" },
        { value: 94, color: "blue" },
        { value: 113, color: "green" },
        { value: 84, color: "blue" },
        { value: 109, color: "blue" },
        { value: 266, color: "pink" },
        { value: 126, color: "pink" }
    ],
    "Br⁻": [
            { value: 81, color: "blue" },
            { value: 98, color: "blue" },
            { value: 87, color: "blue" },
            { value: 103, color: "blue" },
            { value: 119, color: "blue" },
            { value: 188, color: "pink" },
            { value: 281, color: "pink" },
            { value: 361, color: "green"},
            { value: 297, color: "blue" },
            { value: 200, color: "blue" },
            { value: 184, color: "blue" },
            { value: 225, color: "blue" },
            { value: 215, color: "blue" },
            { value: 279, color: "blue" },
            { value: 367, color: "green"},
            { value: 224, color: "blue" },
            { value: 219, color: "blue" },
            { value: 219, color: "blue" },
            { value: 272, color: "blue" },
            { value: 216, color: "blue" },
            { value: 296, color: "blue" },
            { value: 267, color: "blue" },
            { value: 292, color: "blue" },
            { value: 449, color: "gray" },
            { value: 248, color: "blue" }
        ],
    "Cl⁻": [
        { value: 36.5, color: "blue" },
        { value: 53.5, color: "blue" },
        { value: 42.5, color: "blue" },
        { value: 58.5, color: "blue" },
        { value: 74.5, color: "blue" },
        { value: 143.5, color: "pink" },
        { value: 236.5, color: "pink" },
        { value: 272, color: "blue" },
        { value: 208, color: "blue" },
        { value: 111, color: "blue" },
        { value: 95, color: "blue" },
        { value: 136, color: "blue" },
        { value: 126, color: "blue" },
        { value: 190, color: "blue" },
        { value: 278, color: "blue" },
        { value: 135, color: "blue" },
        { value: 130, color: "blue" },
        { value: 130, color: "blue" },
        { value: 183, color: "blue" },
        { value: 127, color: "blue" },
        { value: 162.5, color: "blue" },
        { value: 133.5, color: "blue" },
        { value: 158.5, color: "blue" },
        { value: 315.5, color: "gray" },
        { value: 159, color: "blue" }
    ],
    "I⁻": [ // Corrected from "J⁻" to "I⁻"
        { value: 128, color: "blue" },
        { value: 145, color: "blue" },
        { value: 134, color: "blue" },
        { value: 150, color: "blue" },
        { value: 166, color: "blue" },
        { value: 235, color: "pink" },
        { value: 328, color: "pink" },
        { value: 455, color: "pink" },
        { value: 391, color: "blue" },
        { value: 294, color: "blue" },
        { value: 278, color: "blue" },
        { value: 319, color: "blue" },
        { value: 309, color: "blue" },
        { value: 373, color: "blue" },
        { value: 461, color: "pink" },
        { value: 318, color: "blue" },
        { value: 313, color: "blue" },
        { value: 313, color: "blue" },
        { value: 366, color: "blue" },
        { value: 310, color: "blue" },
        { value: 437, color: "orange" },
        { value: 408, color: "blue" },
        { value: 433, color: "yellow" },
        { value: 590, color: "pink" },
        { value: 342, color: "blue" }
    ],
    "NO₃⁻": [
        { value: 63, color: "blue" },
        { value: 80, color: "blue" },
        { value: 69, color: "blue" },
        { value: 85, color: "blue" },
        { value: 101, color: "blue" },
        { value: 170, color: "blue" },
        { value: 263, color: "gray" },
        { value: 325, color: "blue" },
        { value: 261, color: "blue" },
        { value: 164, color: "blue" },
        { value: 148, color: "blue" },
        { value: 189, color: "blue" },
        { value: 179, color: "blue" },
        { value: 243, color: "gray" },
        { value: 331, color: "blue" },
        { value: 188, color: "blue" },
        { value: 183, color: "blue" },
        { value: 183, color: "blue" },
        { value: 236, color: "blue" },
        { value: 180, color: "blue" },
        { value: 242, color: "blue" },
        { value: 213, color: "blue" },
        { value: 238, color: "blue" },
        { value: 395, color: "blue" },
        { value: 212, color: "blue" }
    ],
    "S²⁻": [
        { value: 34, color: "blue" },
        { value: 68, color: "blue" },
        { value: 46, color: "blue" },
        { value: 78, color: "blue" },
        { value: 110, color: "blue" },
        { value: 248, color: "pink" },
        { value: 434, color: "pink" },
        { value: 233, color: "pink" },
        { value: 169, color: "gray" },
        { value: 72, color: "gray" },
        { value: 56, color: "gray" },
        { value: 97, color: "pink" },
        { value: 87, color: "pink" },
        { value: 151, color: "pink" },
        { value: 239, color: "pink" },
        { value: 96, color: "pink" },
        { value: 91, color: "pink" },
        { value: 91, color: "pink" },
        { value: 144, color: "pink" },
        { value: 88, color: "pink" },
        { value: 208, color: "gray" },
        { value: 150, color: "gray" },
        { value: 200, color: "gray" },
        { value: 514, color: "pink" },
        { value: 120, color: "gray" }
    ],
    "SO3²⁻": [
        { value: 82, color: "blue" },
        { value: 116, color: "blue" },
        { value: 94, color: "blue" },
        { value: 126, color: "blue" },
        { value: 158, color: "blue" },
        { value: 296, color: "pink" },
        { value: 482, color: "pink" },
        { value: 281, color: "yellow" },
        { value: 217, color: "pink" },
        { value: 120, color: "pink" },
        { value: 104, color: "green" },
        { value: 145, color: "green" },
        { value: 135, color: "pink" },
        { value: 199, color: "yellow" },
        { value: 287, color: "pink" },
        { value: 144, color: "orange" },
        { value: 139, color: "pink" },
        { value: 139, color: "pink" },
        { value: 192, color: "pink" },
        { value: 136, color: "pink" },
        { value: 352, color: "yellow" },
        { value: 294, color: "orange" },
        { value: 344, color: "gray" },
        { value: 658, color: "pink" },
        { value: 168, color: "pink" }
    ],
    "HSO4²⁻": [
        { value: 98, color: "blue" },
        { value: 115, color: "blue" },
        { value: 104, color: "blue" },
        { value: 120, color: "blue" },
        { value: 136, color: "blue" },
        { value: 205, color: "yellow" },
        { value: 298, color: "yellow" },
        { value: 395, color: "yellow" },
        { value: 331, color: "yellow" },
        { value: 234, color: "yellow" },
        { value: 218, color: "yellow" },
        { value: 259, color: "yellow" },
        { value: 249, color: "yellow" },
        { value: 313, color: "yellow" },
        { value: 401, color: "pink" },
        { value: 258, color: "yellow" },
        { value: 253, color: "yellow" },
        { value: 253, color: "yellow" },
        { value: 306, color: "yellow" },
        { value: 250, color: "yellow" },
        { value: 347, color: "yellow" },
        { value: 318, color: "yellow" },
        { value: 343, color: "yellow" },
        { value: 500, color: "yellow" },
        { value: 282, color: "gray" }
    ],
    "SO4²⁻": [
        { value: 98, color: "blue" },
        { value: 132, color: "blue" },
        { value: 110, color: "blue" },
        { value: 142, color: "blue" },
        { value: 174, color: "blue" },
        { value: 312, color: "green" },
        { value: 498, color: "pink" },
        { value: 297, color: "gray" },
        { value: 233, color: "pink" },
        { value: 136, color: "green" },
        { value: 120, color: "blue" },
        { value: 161, color: "blue" },
        { value: 151, color: "blue" },
        { value: 215, color: "blue" },
        { value: 98, color: "pink" },
        { value: 203, color: "pink" },
        { value: 160, color: "blue" },
        { value: 155, color: "blue" },
        { value: 155, color: "blue" },
        { value: 208, color: "blue" },
        { value: 152, color: "blue" },
        { value: 400, color: "blue" },
        { value: 342, color: "blue" },
        { value: 392, color: "blue" },
        { value: 706, color: "yellow" },
        { value: 184, color: "pink" }
    ],
    "HCO₃⁻": [
        { value: 62, color: "blue" },
        { value: 79, color: "blue" },
        { value: 68, color: "blue" },
        { value: 84, color: "blue" },
        { value: 100, color: "blue" },
        { value: 169, color: "yellow" },
        { value: 262, color: "yellow" },
        { value: 323, color: "yellow" },
        { value: 259, color: "blue" },
        { value: 162, color: "blue" },
        { value: 146, color: "blue" },
        { value: 187, color: "yellow" },
        { value: 177, color: "yellow" },
        { value: 241, color: "yellow" },
        { value: 329, color: "blue" },
        { value: 186, color: "yellow" },
        { value: 181, color: "yellow" },
        { value: 181, color: "yellow" },
        { value: 234, color: "yellow" },
        { value: 178, color: "blue" },
        { value: 239, color: "yellow" },
        { value: 210, color: "yellow" },
        { value: 235, color: "yellow" },
        { value: 392, color: "yellow" },
        { value: 210, color: "blue" }
    ], "CO₃²⁻": [
        { value: 62, color: "blue" },
        { value: 96, color: "blue" },
        { value: 74, color: "blue" },
        { value: 106, color: "blue" },
        { value: 138, color: "blue" },
        { value: 276, color: "pink" },
        { value: 462, color: "pink" },
        { value: 261, color: "yellow" },
        { value: 197, color: "pink" },
        { value: 100, color: "pink" },
        { value: 84, color: "pink" },
        { value: 125, color: "pink" },
        { value: 115, color: "pink" },
        { value: 179, color: "yellow" },
        { value: 167, color: "pink" },
        { value: 124, color: "pink" },
        { value: 119, color: "pink" },
        { value: 119, color: "pink" },
        { value: 172, color: "pink" },
        { value: 116, color: "pink" },
        { value: 292, color: "orange" },
        { value: 234, color: "orange" },
        { value: 284, color: "orange" },
        { value: 598, color: "orange" },
        { value: 148, color: "pink" }
    ],
    "SiO₄⁴⁻": [
        { value: 78, color: "pink" },
        { value: 112, color: "yellow" },
        { value: 90, color: "pink" },
        { value: 122, color: "blue" },
        { value: 154, color: "blue" },
        { value: 292, color: "yellow" },
        { value: 478, color: "yellow" },
        { value: 277, color: "yellow" },
        { value: 213, color: "pink" },
        { value: 116, color: "pink" },
        { value: 100, color: "pink" },
        { value: 141, color: "pink" },
        { value: 131, color: "pink" },
        { value: 195, color: "yellow" },
        { value: 283, color: "pink" },
        { value: 140, color: "yellow" },
        { value: 135, color: "yellow" },
        { value: 135, color: "yellow" },
        { value: 188, color: "yellow" },
        { value: 132, color: "green" },
        { value: 340, color: "yellow" },
        { value: 282, color: "yellow" },
        { value: 332, color: "yellow" },
        { value: 656, color: "yellow" },
        { value: 164, color: "pink" }
    ],
    "H₂PO₄⁻": [
        { value: 98, color: "blue" },
        { value: 115, color: "blue" },
        { value: 104, color: "blue" },
        { value: 120, color: "blue" },
        { value: 136, color: "blue" },
        { value: 205, color: "blue" },
        { value: 298, color: "blue" },
        { value: 395, color: "yellow" },
        { value: 331, color: "blue" },
        { value: 234, color: "blue" },
        { value: 218, color: "blue" },
        { value: 259, color: "blue" },
        { value: 249, color: "blue" },
        { value: 313, color: "yellow" },
        { value: 401, color: "gray" },
        { value: 258, color: "yellow" },
        { value: 253, color: "yellow" },
        { value: 253, color: "yellow" },
        { value: 306, color: "yellow" },
        { value: 250, color: "blue" },
        { value: 347, color: "yellow" },
        { value: 318, color: "yellow" },
        { value: 343, color: "yellow" },
        { value: 500, color: "green" },
        { value: 282, color: "blue" }
    ],
    "HPO₄²⁻": [
        { value: 98, color: "blue" },
        { value: 132, color: "blue" },
        { value: 110, color: "yellow" },
        { value: 142, color: "blue" },
        { value: 174, color: "blue" },
        { value: 312, color: "yellow" },
        { value: 498, color: "green" },
        { value: 297, color: "yellow" },
        { value: 233, color: "green" },
        { value: 136, color: "green" },
        { value: 120, color: "green" },
        { value: 161, color: "yellow" },
        { value: 151, color: "green" },
        { value: 215, color: "pink" },
        { value: 303, color: "green" },
        { value: 160, color: "yellow" },
        { value: 155, color: "yellow" },
        { value: 155, color: "yellow" },
        { value: 208, color: "yellow" },
        { value: 152, color: "green" },
        { value: 400, color: "yellow" },
        { value: 342, color: "yellow" },
        { value: 392, color: "yellow" },
        { value: 706, color: "yellow" },
        { value: 184, color: "pink" }
    ],
    "PO₄³⁻": [
        { value: 98, color: "blue" },
        { value: 149, color: "grey" },
        { value: 116, color: "pink" },
        { value: 164, color: "blue" },
        { value: 212, color: "blue" },
        { value: 419, color: "pink" },
        { value: 698, color: "yellow" },
        { value: 793, color: "pink" },
        { value: 601, color: "pink" },
        { value: 310, color: "pink" },
        { value: 262, color: "pink" },
        { value: 385, color: "pink" },
        { value: 353, color: "pink" },
        { value: 547, color: "pink" },
        { value: 311, color: "pink" },
        { value: 382, color: "pink" },
        { value: 367, color: "pink" },
        { value: 367, color: "pink" },
        { value: 526, color: "pink" },
        { value: 358, color: "pink" },
        { value: 151, color: "pink" },
        { value: 122, color: "pink" },
        { value: 147, color: "pink" },
        { value: 304, color: "pink" },
        { value: 454, color: "pink" },
    ],
    "HCOO⁻": [
        { value: 46, color: "blue" },
        { value: 63, color: "blue" },
        { value: 52, color: "blue" },
        { value: 68, color: "blue" },
        { value: 84, color: "blue" },
        { value: 153, color: "blue" },
        { value: 246, color: "blue" },
        { value: 291, color: "blue" },
        { value: 227, color: "blue" },
        { value: 130, color: "blue" },
        { value: 114, color: "blue" },
        { value: 155, color: "blue" },
        { value: 145, color: "blue" },
        { value: 209, color: "blue" },
        { value: 297, color: "blue" },
        { value: 154, color: "blue" },
        { value: 149, color: "blue" },
        { value: 149, color: "blue" },
        { value: 202, color: "blue" },
        { value: 146, color: "blue" },
        { value: 191, color: "blue" },
        { value: 162, color: "blue" },
        { value: 187, color: "blue" },
        { value: 344, color: "blue" },
        { value: 178, color: "blue" },
    
    ],
   
    "CH₃COO⁻": [
        { value: 60, color: "blue" },
        { value: 77, color: "blue" },
        { value: 66, color: "blue" },
        { value: 82, color: "blue" },
        { value: 98, color: "blue" },
        { value: 167, color: "blue" },
        { value: 260, color: "blue" },
        { value: 319, color: "blue" },
        { value: 255, color: "blue" },
        { value: 158, color: "blue" },
        { value: 142, color: "blue" },
        { value: 183, color: "blue" },
        { value: 173, color: "blue" },
        { value: 237, color: "grey" },
        { value: 325, color: "blue" },
        { value: 182, color: "blue" },
        { value: 177, color: "blue" },
        { value: 177, color: "blue" },
        { value: 230, color: "blue" },
        { value: 174, color: "blue" },
        { value: 233, color: "grey" },
        { value: 204, color: "grey" },
        { value: 229, color: "blue" },
        { value: 386, color: "pink" },
        { value: 206, color: "blue" }
    ],
    "C₆H₅COO⁻": [
        { value: 284, color: "pink" },
        { value: 301, color: "blue" },
        { value: 290, color: "blue" },
        { value: 306, color: "blue" },
        { value: 322, color: "blue" },
        { value: 391, color: "green" },
        { value: 484, color: "pink" },
        { value: 767, color: "pink" },
        { value: 703, color: "pink" },
        { value: 606, color: "pink" },
        { value: 590, color: "green" },
        { value: 631, color: "pink" },
        { value: 621, color: "pink" },
        { value: 685, color: "pink" },
        { value: 773, color: "green" },
        { value: 630, color: "pink" },
        { value: 625, color: "pink" },
        { value: 625, color: "pink" },
        { value: 678, color: "pink" },
        { value: 622, color: "pink" },
        { value: 905, color: "pink" },
        { value: 876, color: "pink" },
        { value: 901, color: "pink" },
        { value: 1058, color: "pink" },
        { value: 654, color: "pink" }
    ]
};

function initializeTable() {
    const table = document.getElementById('solubility-table');
    const thead = table.querySelector('thead tr');
    const tbody = table.querySelector('tbody');

    cations.forEach(cation => {
        const th = document.createElement('th');
        th.innerHTML = cation;
        thead.appendChild(th);
    });

    for (const [anion, dataArray] of Object.entries(solubilityData)) {
        const tr = document.createElement('tr');

        const anionCell = document.createElement('td');
        anionCell.innerHTML = anion.replace(/(\d+)/g, "<sub>$1</sub>").replace(/(\^)/g, "<sup>$1</sup>");
        tr.appendChild(anionCell);

        cations.forEach((cation, index) => {
            const td = document.createElement('td');

            if (dataArray[index]) {
                td.textContent = dataArray[index].value;
                if (dataArray[index].color) {
                    td.classList.add(dataArray[index].color);
                }
            } else {
                td.textContent = "—";
            }

            tr.appendChild(td);
        });

        tbody.appendChild(tr);
    }
}

document.addEventListener('DOMContentLoaded', initializeTable);
